name 'jdowning/rbenv'
version '1.3.1'
source 'https://github.com/justindowning/puppet-rbenv'
author 'Justin Downing'
license 'Apache License, Version 2.0'
summary 'Setup rbenv ruby manager for systemwide use'
description 'Setup rbenv ruby manager for systemwide use'
project_page 'https://github.com/justindowning/puppet-rbenv'
dependency 'puppetlabs/vcsrepo', '>=1.1.0'
dependency 'puppetlabs/stdlib', '>=4.1.0'
